name: "Basic HA Addon"
version: "1.0-SNAPSHOT"
slug: "basic-ha-addon"
description: >-
  Basic JVM based HA addon
arch:
  - amd64
  - arm
  - arm64
url: "https://github.com/DonRobo/basic-ha-addon"
ports:
  8080/tcp: 8080
image: ghcr.io/donrobo/basic-ha-addon
